### ISSUE TITLE
Missing 'User management' in 'Tools' combo box on main page of internal catalog.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#102]
According:
Test Case ODN-40 :: Version : 1 :: Add new user and its role (valid);

in internal catalog has to be Tools combo box with User Management Item.

ODN-362:Modify user's profile and its role (missing mandatory attributes)
ODN-360:Modify user's own user profile (missing mandatory attributes)
ODN-353:Add new user and its role (missing mandatory attributes)
ODN-44:Modify user's own user profile (valid)
ODN-42:Modify user's profile and its role (valid)
ODN-40:Add new user and its role (valid)

**Comment by skrchnavy** [comment]
fixed in OpenDataNode/ckanext-odn-theme@157a7d97cb9abda7a8fdf1466655379a4259a3f5
