### ISSUE TITLE
Midpoint common user (non administrator) can create another user with role administrator.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#104]
Is OK if I did this?

I logged into midpoint as casadmin.
I created user adriana with administrator role, reconcile, save. Close browser.
I logged into midpoint as administrator adriana, edit my role to user, reconcile. Save.
I click into menu New User and I created administrator Peter. Peter is new administrator.
No err msg was raised. Non administrator adriana created administrator Peter.

**Comment by peterklimo** [comment]
not reproducable on my environment, also not reproducable on "oskar" server

**Comment by eea71** [comment]
Whati is not reproducable? I did it on "Oskar" now. User Adriana non administrator create user Kazimir Kazimir. Read how to do it exactly. I wrote exact steps.

**Comment by peterklimo** [comment]
are you sure you clicked on reconcile after you changed the user role ?

**Comment by eea71** [comment]
Yes I am. After reconcile and save user adriana dont close browser but continue with user creating.

**Comment by peterklimo** [comment]
clarified.
credentials for actual logged in user are set during login procedure, they are not updated after you changed it in the application (even if you enable reconcile). you need to logout from application and login again.
issues regarding application timeout and logout are reported as separate issue

**Comment by skrchnavy** [comment]
@peterklimo what is result of this issue? fixed or invalid?

**Comment by peterklimo** [comment]
invalid
