### ISSUE TITLE
Midpoint create user too few mandatory fields required.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#105]
To create new user is necessary only Name and Password.
The rest of fields could be empty. For us it is not correct situation. We probably don't need such user.

ODN-362:Modify user's profile and its role (missing mandatory attributes)
ODN-360:Modify user's own user profile (missing mandatory attributes)
ODN-353:Add new user and its role (missing mandatory attributes)
ODN-40 :: Version : 1 :: Add new user and its role (valid)

**Comment by katkav** [comment]
Yes, you're right. The new configuration which requires to fill first name, family name, name, role, organization was prepared but was not included in the last release.

**Comment by eea71** [comment]
Bugs:
Password is NOT mandatory at the moment! 
Email address has no validation!
Organization can be anything!

**Comment by OskarStoffan** [comment]
#97

**Comment by peterklimo** [comment]
"Password is NOT mandatory at the moment!" - fixed in 1.0.3
Email is mandatory but is not checked for email pattern with @
Organization will be redesigned in next release
