### ISSUE TITLE
Filter for scheduller.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#113]
When I schedule pipeline, application open UV scheduler tab. 
But I see all scheduled pipelines.

Wished functionality is to see scheduling rules for selected pipeline only.
Test Case ODN-29 :: Version : 1 :: Modify pippeline scheduling information
 Test Case ODN-30 :: Version : 1 :: Create pipeline scheduling information

**Comment by skrchnavy** [comment]
depends on UnifiedViews/Core#384
