### ISSUE TITLE
Redirect from HTTP to HTTPS when user access 'internal' applications of ODN

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#115]
If you access ODN's services that require HTTPS (e.g., InternalCatalog, UnifiedViews) using HTTP instead of HTTPS, your request is handled by CKAN (PublicCatalog) and you are presented with HTTP 404 error. It would be helpful to present the user a more descriptive message that suggests that HTTPS needs to be used.

Context: ODN 1.0.1 installed from odn-simple Debian package.

**Comment by skrchnavy** [comment]
Redirect from http to https shall be implemented instead of proxying public catalog.

**Comment by skrchnavy** [comment]
fixed in /OpenDataNode/odn-box@9cf5b556556282e026a0cc679e7292321dfd28a2

**Comment by Jan-Marcek** [comment]
also ckanext-odn-ic2pc-sync has to support https. https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/issues/15

**Comment by skrchnavy** [comment]
included in odn box v1.0.2
