### ISSUE TITLE
Problem with association of pipeline.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#116]
I associated new pipeline to dataset. I configured it manually.
Then I disassociated this pipeline.
Consequently I wanted associate new existing pipeline to this dataset. 
BUT in offered pipelines this one was missing.

Note: Later I created 5 copies of this pipeline ( after its disasociation ) through UV button COPY.
These newly created copies was offered me to associate. 
Workaround: Seems like some troubles to associate the same pipeline, however it was already disasociated. Somewhere stays something remember.

ODN-363:Associate an existing disassociated pipeline

**Comment by eea71** [comment]
New research: For newly created dataset I didnt see once already unassociated pipeline.

**Comment by mvi-eea-sk** [comment]
@skrchnavy and @eea71 
this was "fixed" in 1.0.2 release, so you can see and associate all unassociated pipelines (even another organization pipelines)
this will be properly fixed in 1.0.3

**Comment by skrchnavy** [comment]
@eea71 please verify in 1.0.2
