### ISSUE TITLE
Default locale in UnifiedViews' backend-config.properties should be English

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#118]
While the frontend-config.properties of UnifiedViews has the default locale set to `en` (English), backend-config.properties defaults locale to `sk` (Slovak). The default locale should be `en` in both cases.

I'm using ODN 1.0.1 installed from the odn-simple Debian package.

**Comment by skrchnavy** [comment]
depends on UnifiedViews/Packages#31

**Comment by Jan-Marcek** [comment]
https://github.com/UnifiedViews/Packages/commit/b23d9349992ee72edd5a08dc78ef364479fdba75

**Comment by skrchnavy** [comment]
included in UV core v2.0.2
