### ISSUE TITLE
No preview available for csv file.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#119]
I created dataset and pipeline with creating resource .csv. In detail of dataset after adding resource I dont see preview.
![image](https://cloud.githubusercontent.com/assets/10993265/7648593/0de882ac-fae5-11e4-9192-ba7fa29f5d21.png)

ODN-23:List available resources for a dataset (select resource name)
ODN-104:List available resources for a dataset (select more information)

**Comment by skrchnavy** [comment]
Issue is caused how is datapreview implemented in CKAN. It uses external service to render csv/xls data in file store and that service has to have access to data. (for more details see: http://docs.ckan.org/en/latest/maintaining/data-viewer.html#data-explorer )

DataGovUK group created extension that handles the preview localy (no service): https://github.com/datagovuk/ckanext-datapreview

**Comment by eea71** [comment]
NOTE and possible reason: The server with installed application is not accessible from outside.

**Comment by skrchnavy** [comment]
@hanecak do we want to fix this issue? that is to support previews even for server that is not accessible from the internet?
There could be setup when ODN/IC is not accessible from internet only from local sites. Or other reasons.

**Comment by hanecak** [comment]
@skrchnavy in short: Yes, we do want to fix that. ODN/InternalCatalog as a whole is "private stuff", yet we do want data preview to work also in there.

Longer story: According to COMSODE Methodology, dataset publisher - during preparation phase - will be working primarily in ODN/InternalCatalog and most often keep the stuff "private" while it not yet fully ready for public consumption. And ODN/InternalCatalog is not accessible "from the outside", thus private datasets (and resources) will neither be accessible "from the outside".

That, combined with this issue, will limit data publisher in his work and slow down dataset publication process: publisher wont be able to get quick preview of his work-in-progress, thus he will be (among other things) not able to properly validate the dataset before official release.

Please, investigate re-use of https://github.com/datagovuk/ckanext-datapreview (or some other options) to fix this.

**Comment by eea71** [comment]
I found out this: I don't see preview of .csv file for PRIVATE dataset. For PUBLIC is available and displayed. In case of changing from PRIVATE to PUBLIC  and vice versa behaviour is still same.

**Comment by eea71** [comment]
https://ast.comsode.eea.sk/internalcatalog/dataset/testdatasetdefaultalways/resource/a22bdc6d-6e55-4493-ab48-71f9ce93641c#

preview is not available...

**Comment by skrchnavy** [comment]
the link redirects to cas so this could be the issue with preview using external service

**Comment by hanecak** [comment]
Fixing this (with re-use of https://github.com/datagovuk/ckanext-datapreview) should fix also #197 and #235.

**Comment by Jan-Marcek** [comment]
The server was not visible from internet therefore csv plugin was unable to show preview. We can close it.
