### ISSUE TITLE
Impossible to publish resource at the Facebook and Google+.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#120]
I had public dataset and resouce zmluvicky.zip, wanted to publish at the FB.
![facebook](https://cloud.githubusercontent.com/assets/10993265/7652550/0a4cfc58-fb0e-11e4-8352-ce09cd3d8c80.jpg)

Condition from install guide: Configure debian box properly, mainly hostname shall be defined as box visible from external network.
Possible reason: The server with installed application is not accessible from outside.

**Comment by eea71** [comment]
For Google+ application offered to add comment, but link to ODN resource is not present.

**Comment by skrchnavy** [comment]
@mvi-eea-sk is this bug in vanilla CKAN?

**Comment by mvi-eea-sk** [comment]
@eea71 can you confirm this problem is actual

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that:

1. bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older)
2. this behaviour is from upstream (CKAN), so if it is deemed a bug again, we will raise it with upstream

Having said that, whoever is negatively affected by this again in the future, please reopen this.
