### ISSUE TITLE
Public dataset in the internal catalogue is not synchronized to the public catalogue

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#121]
If I mark the visibility of a dataset in the internal catalogue (belonging to the default COMSODE organization) as public, it is not synchronized to the public catalogue. It remains to be visible only in the internal catalogue, even though it no longer has the "private" flag.

I'm using ODN 1.0.1 installed via the odn-simple Debian package. If I recall correctly, dataset synchronization between the internal and the public catalogue worked correctly in the previous release.

TCID: ODN-18

**Comment by skrchnavy** [comment]
Depends on OpenDataNode/ckanext-odn-ic2pc-sync#16
