### ISSUE TITLE
odn-midpoint: Excessive logging

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#122]
odn-midpoint creates a lot of logs. For example, it generated more than 500 MB of logs per 1 day on my ODN 1.0.1 server using odn-simple 1.0.1 Debian package. Reducing the volume of logs would be appreciated. For example, the default log level can be set higher than `TRACE`.

**Comment by skrchnavy** [comment]
depends on OpenDataNode/odn-box#20

**Comment by Jan-Marcek** [comment]
it was fixed by https://github.com/OpenDataNode/odn-box/blob/develop/midpoint/conf/web.xml#L92

It was caused by the fact that we were using snapshot version of midpoint.

**Comment by Jan-Marcek** [comment]
not fixed. Not enough.

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/odn-box/commit/916b60121eaa23e1a6925e2663bad90a5b5afcc1
