### ISSUE TITLE
Error synchronizing public catalog after reconfiguration ini file.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#124]
Opens CKAN ini configuration file (/etc/odn-simple/odn-ckan-ic/production.ini), modifies the URL of public catalog and the API key this way.

#odn.ic2pc.src.ckan.url = http://localhost:9080/internalcatalog
#odn.ic2pc.dst.ckan.url = http://ast.comsode.eea.sk
#odn.ic2pc.dst.ckan.api.key =  1d8bf54d-598b-4f41-95a2-0509883771ed

odn.ic2pc.dst.ckan.url = http://demo.ckan.org 
odn.ic2pc.dst.ckan.api.key = 1c60c20f-8735-4906-8246-9dcf9ba88f04

restart apache/ push synchronize with public catalog now. Err msg rised.

![image](https://cloud.githubusercontent.com/assets/10993265/7749686/9aa04768-ffcf-11e4-9c46-e300309e0b7e.png)
ODN-280:Management of default public catalog for publicly available datasets

**Comment by mvi-eea-sk** [comment]
odn.ic2pc.src.ckan.url = http://localhost:9080/internalcatalog
musn't be deleted !
You can change the destination CKAN url and API key but, the source CKAN has to be there too!

**Comment by eea71** [comment]
![image](https://cloud.githubusercontent.com/assets/10993265/8477651/12751e68-20cc-11e5-8372-39804750fb32.png)

**Comment by mvi-eea-sk** [comment]
most likely the user (with that api key) has no rights to edit right for that organization
he has only member role in that organization ... so change the api key to user, who has editor or administrator right in that organization

**Comment by eea71** [comment]
I think this user has rights for it. But try it on ast.comsode.eea.sk; in this moment is production.ini edited the way for this action. Thnx.

**Comment by eea71** [comment]
this is right configuration.

#odn.ic2pc.dst.ckan.url = https://ast.comsode.eea.sk
#odn.ic2pc.dst.ckan.api.key =  1fda8587-9f49-4430-9acc-3db64cab89b2


odn.ic2pc.dst.ckan.url = http://demo.comsode.eu
odn.ic2pc.dst.ckan.api.key = cb81bd0a-8e0e-48b1-95ab-0f10b879465d
