### ISSUE TITLE
Size of Data API window in CKAN

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#125]
Click to 'Data API' button on REST API resource of a dataset. 
Width of CKAN Data API window is not correct (text is not readable).
TCs: ODN-78, ODN-79

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/ckanext-odn-theme/commit/053811593ff1a368db447f8839e4cedcdbc184f6

**Comment by eea71** [comment]
by myself ok!
