### ISSUE TITLE
unifiedviews: Excessive logging

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#128]
Logging of backend and frontend are set to DEBUG level. It should be set to INFO at production.

TCID: ODN-371

**Comment by Jan-Marcek** [comment]
frontend.log
```
2015-05-29 08:58:15,065 [localhost-startStop-1] WARN  Spring Security Debugger -

********************************************************************
**********        Security debugging is enabled.       *************
**********    This may include sensitive information.  *************
**********      Do not use in a production system!     *************
********************************************************************
```

**Comment by Jan-Marcek** [comment]
changed logging level to INFO for frontend https://github.com/UnifiedViews/Core/commit/68ebfa5a058b66f85769462ad1f1fd6d0fec772c

**Comment by Jan-Marcek** [comment]
changed logging level to INFO for backend https://github.com/UnifiedViews/Core/commit/365c7cfc5727a9258780bf8fdcc0b4dbc7ad6ee1

**Comment by skrchnavy** [comment]
Included in UV core v2.0.2

**Comment by Jan-Marcek** [comment]
fixed again https://github.com/UnifiedViews/Core/commit/92c2ee4d857a0982814f1ca966732c30ca48cdca

**Comment by hanecak** [comment]
Yup, this is resolved, but only in the source code, devel branch. But the fix did not kade it into ODN 1.2.0 build so it will be in ODN 1.2.1 .

We will close the issue after solution is confirmed to be working in ODN 1.2.1 release.

**Comment by hanecak** [comment]
Update: Using ODN 1.2.0 (with UnifeidViews 2.2.0) I have 74 MB of data in /var/log/unifiedviews/frontend/catalina.out as a result of past 10 days while doing not that much with ODN/UV.

I'm seeing lots of lines like:

```
2015-12-17 18:00:30,045 [taskScheduler-2] DEBUG org.eclipse.persistence.logging.sql - 2015-12-17 18:00:30.045--ServerSession(1992096457)--Connection(1632781727)--SELECT ID, backend_id, last_update FROM backend_servers
2015-12-17 18:00:36,046 [taskScheduler-2] DEBUG org.eclipse.persistence.logging.sql - 2015-12-17 18:00:36.046--ServerSession(1992096457)--Connection(1911602111)--SELECT ID, backend_id, last_update FROM backend_servers
```

i.e. one such line each few seconds.

Please take one more look at this.

**Comment by tomas-knap** [comment]
In the current master branch, persistence is at DEBUG level - https://github.com/UnifiedViews/Core/blob/master/frontend/src/main/webapp/WEB-INF/classes/logback.xml#L53. In the next release it is already set to be at the level of WARN - https://github.com/UnifiedViews/Core/blob/release/UV_Core_v2.3.0/frontend/src/main/webapp/WEB-INF/classes/logback.xml#L53

**Comment by hanecak** [comment]
OK, so if we resolve https://github.com/UnifiedViews/Core/issues/567 (and not run into more of those) we can have UnifiedViews 2.3.0 in ODN 1.3.0 and thus fix also this. Lets make this a plan for now.

**Comment by hanecak** [comment]
OK, https://github.com/UnifiedViews/Core/issues/567 was resolved and tested few days ago. But it's quite late for ODN 1.3.0 so I'm replanning this for ODN 1.4.0 .

**Comment by Jan-Marcek** [comment]
Unifiedviews pull request: https://github.com/UnifiedViews/Core/pull/583
