### ISSUE TITLE
Internal catalog: size of resources is too low in default installation

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#129]
Size of resource is set to 10 MB . It is too low. For instance SAZP pipelines produce resources with size cca 150 MB 

by default size is set to 10 MB. 
https://github.com/OpenDataNode/odn-box/blob/master/ckan-ic/production.ini#L186

**Comment by skrchnavy** [comment]
@hanecak Do we want to increase the default size in the installation? Isn't 10MB for files enough?

**Comment by hanecak** [comment]
The idea behind re-use of CKAN in ODN is to stay as close to upstream as possible as maintaining differences is expensive.

In this particular case I think the cost outweighs the benefit so:
1. we will leave the default same as in CKAN (i.e. "wont fix")
2. whoever wants higher limit, can follow instructions in FAQ: https://utopia.sk/wiki/pages/viewpage.action?pageId=53379826#FrequentlyAskedQuestions%28FAQ%29-HowcanIloadfilesbiggerthan10MB%28CKANdefault%29?
