### ISSUE TITLE
Syntax error when user session in UnifiedViews expires

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#130]
When user session in UnifiedViews expires, CAS login request appears reporting syntax error: `(SyntaxError) : Unexpected identifier - Original JSON-text:PE html>`

![screenshot](https://cloud.githubusercontent.com/assets/198642/7835863/3e49f584-047c-11e5-9bce-1ee24a71db67.png)

Also note that the login request popup appears twice, possibly as a result of 2 successive session timeouts.

Context: I'm using the Debian package odn-simple in the version 1.0.1.

**Comment by eea71** [comment]
After logout in IC and Midpoint, UV opened at the next tab shows one this page. But it is ok. In ODN 1.2.0 seems is ok.

**Comment by skrchnavy** [comment]
It is not nice to see login screen but refresh of browser causes proper redirect to CAS login screen
