### ISSUE TITLE
Log out problem

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#133]
When 'log out' is clicked in ODN/IC, user is logged out from ODN/IC and ODN/MidPoint (user remains logged in in ODN/UV).
When 'log out' is clicked in ODN/UV, user is logged out from ODN/UV and ODN/MidPoint (user remains logged in in ODN/IC).
When 'log out' is clicked in ODN/MidPoint, user is logged out from ODN/MidPoint (user remains logged in in ODN/UV and ODN/IC).

TC ID: ODN-64

**Comment by skrchnavy** [comment]
@OskarStoffan isn't this duplicate of #95 ?

**Comment by peterklimo** [comment]
there is only problem open from this bug report: IC/CKAN does not respond to logout notifications from other applications

**Comment by peterklimo** [comment]
problem of the cas ckan extension, will be implemented by dominik kapisinsky

**Comment by mvi-eea-sk** [comment]
@peterklimo implemented kapisinsky's changes into ckanext-odn-cas plugin

**Comment by peterklimo** [comment]
@mvi-eea-sk please provide a reference in the repository to the fix

**Comment by peterklimo** [comment]
related to https://team.eea.sk/jira/browse/COMSODE-1194
