### ISSUE TITLE
sto_79: Verify the configuration of external catalog

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/open-data-node#135]
[sto_79: Verify the configuration of external catalog](https://utopia.sk/wiki/x/y4AuAw)

**Comment by mvi-eea-sk** [comment]
commit: https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/9594af8b962b2b9cd37fac48f0df3a75246a2486

**Comment by skrchnavy** [comment]
Duplicated by #176
