### ISSUE TITLE
Full text search for dataset searching is not correct - PC.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#141]
In this moment in https://ast.comsode.eea.sk/
there is several datasets, which has the name dataset at the Title and at the URL.
If I put this key into search "dataset" I obtain only 1 result.
But there is minimally 4 datasets with this string at the Title/URL.

TCID: ODN-27

**Comment by eea71** [comment]
problem with *set* in PC different result like in IC

**Comment by eea71** [comment]
actual environment ast.comsode.eea.sk
![image](https://cloud.githubusercontent.com/assets/10993265/8475909/3318e92a-20bc-11e5-83c9-12cb450d713d.png)

**Comment by peterklimo** [comment]
no item is missing, it all depends on requirements how the fulltext search
should work
if you write "test*" it returns all datasets where title and description
contains word "title", not "titles" or "titlestitlestitles"
only exception is camel case, in this case word is tokenized and treated as
separate words, that is the reason you see setAndTest in results but no
testandset

**Comment by eea71** [comment]
I have data in IC and in PC for this search same. Try this in IC and try this in PC. I obtained 2 different results. 4 results for IC and 3 results for PC. I don't know why there is difference. Minimally I think it would be the same.

**Comment by skrchnavy** [comment]
My test:
![image](https://cloud.githubusercontent.com/assets/7057580/8480988/2a231bcc-20e1-11e5-80e6-ce050e7babcd.png)
and
![image](https://cloud.githubusercontent.com/assets/7057580/8480995/3b3b8df4-20e1-11e5-89d6-796c6c0fc04e.png)

shows same results in both catalogs

**Comment by peterklimo** [comment]
i am also getting the same results in both catalogs, please specifiy your
test case inputs

**Comment by peterklimo** [comment]
based on deep analysis we found following:

the difference between results in IC and PC are caused by different reindexing and indexing strategy in both catalogs. in the IC the solr index is updated directly after update of IC database (the dataset is changed, added or deleted) while PC reindexing is fired by cron at certain time. it means before the reindexing of PC is done the search results in IC and PC will differ.

**Comment by skrchnavy** [comment]
@eea71 to retest

**Comment by eea71** [comment]
now seems is ok in pre-release 1.1.2

**Comment by skrchnavy** [comment]
@eea71 / @peterklimo v1.1.2 released, is it fixed?
