### ISSUE TITLE
SOLR admin is visible from outside on http

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/open-data-node#142]
Wrong configuration of tomcat that listens by default on all interfaces.

TCID: ODN-378

**Comment by OskarStoffan** [comment]
please add some description how to test whether this is resolved or not

**Comment by peterklimo** [comment]
solr admin is visible on following url:

http://<hostname>:8983/solr

this has to be disabled, only url where it has to be visible is

http://localhost:8983/solr

in other words solr should not be visible from outside

**Comment by skrchnavy** [comment]
Is there any commit that resolves the issue?

**Comment by peterklimo** [comment]
see comit 32692f0
