### ISSUE TITLE
Pipeline execution bug.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#143]
When a pipeline is associated with a dataset and is executed by 'Execute now' (from internal catalog), it fails. The same pipeline when executed directly from ODN/UV (in Pipelines or Execution monitor tab) finishes with status OK (resources in CKAN are created correctly in this case).

Type:
PIPELINE_ERROR
Short message:
Pipeline execution failed.
Message:
Execution failed because: Could not obtain dataset from CKAN.eu.unifiedviews.dpu.DPUException: Could not obtain dataset from CKAN. at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:181) at eu.unifiedviews.plugins.loader.filestockan.FilesToCkan.innerExecute(FilesToCkan.java:197) at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) at java.lang.Thread.run(Thread.java:745)

**Comment by skrchnavy** [comment]
reported in OpenDataNode/UVPlugin-filesToCKAN#7

**Comment by mkl-eea-sk** [comment]
Which environment I can use for testing? At ideal, the host which 
triggered the error please.

**Comment by eea71** [comment]
https://ast.comsode.eea.sk/internalcatalog/

user:casadmin
pwd according install manual

https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.2

**Comment by mkl-eea-sk** [comment]
eea71 triggers this error using different technique from https://github.com/OpenDataNode/UVPlugin-filesToCKAN/issues/7. Here, the ppl is executed from CKAN, in https://github.com/OpenDataNode/UVPlugin-filesToCKAN/issues/7 the ppl is "run for first time". This may or may not be relevant - it may or may not be two bugs.

**Comment by eea71** [comment]
This bug appears each time pipeline is running in actual tested release on environment mentioned above. Each running from ODN/IC is failed and each running from ODN/UV is scuccessfull. There is no problem to simulate this bug several times. And unfortunately, I think this bug wasn't in previous version. :-(

**Comment by eea71** [comment]
In actual tested versions on https://odn-trencin/internalcatalog and https://demo.comsode.eu/internalcatalog is not possible to simulate it. Seems was fixed.

**Comment by skrchnavy** [comment]
closing as fixed in 1.0.3.
