### ISSUE TITLE
Midpoint User Edit Message!

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#145]
I clicked at the existing user and remove Full Name. Appears err msg window.
![image](https://cloud.githubusercontent.com/assets/10993265/7935079/10b21050-092e-11e5-9ac2-4210be29a41b.png)

ODN-362:Modify user's profile and its role (missing mandatory attributes)
ODN-360:Modify user's own user profile (missing mandatory attributes)
ODN-42:Modify user's profile and its role (valid)

**Comment by peterklimo** [comment]
fixed and tested in 1.0.2

**Comment by skrchnavy** [comment]
@eea71 please verify in 1.0.2

**Comment by eea71** [comment]
If something making problems, remove IT. ;-)
