### ISSUE TITLE
Midpoint Disabled user logged into IC and UV.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#147]
I created user Administrator in midpoint. I saved. Consequently I edited and Disabled this user.
I close all windows. I open FF nad logged with this disabled user into IC, via Tools I logged into UV.
Without Problems!!! Via Tools I wanted to log into User management. I obtained this.
![image](https://cloud.githubusercontent.com/assets/10993265/7935529/fb8d605e-0931-11e5-98bc-3cf764ec3de5.png)

Only logging into Midpoint was not possible.
![image](https://cloud.githubusercontent.com/assets/10993265/7935557/2d9bf812-0932-11e5-87a3-ca7057618df7.png)

ODN-44:Modify user's own user profile (valid)

**Comment by skrchnavy** [comment]
@eea71 did you pressed reconcile? You shall not be logged into CAS (login shall be unsuccessful)

**Comment by peterklimo** [comment]
fixed in 1.0.3
