### ISSUE TITLE
Missing Rest API button in Public catalog.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#148]
I created pipeline with otuput to DPU uv-l-relationalToCkan. In internal catalog I see REST API button with links to data. Dataset is PUBLIC! In public catalog I dont see button REST API.

ODN-78 :: Version : 1 :: Retrieving public data from a dataset via REST API

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/e6ec58b77e58005cce007cb66ab628c7e925775a

Cause: synchronizing resource failed because of wrongly set indexes when creating datastore resource

@eea71 I also deployed it on ast test server
