### ISSUE TITLE
missing licence

### ISSUE THREAD

**Issue by maurino1973** [OpenDataNode/open-data-node#149]
There is no possibile to add a new licence (e.g. the italian  open data licence 2.0 http://www.dati.gov.it/iodl/2.0/). I suggest to 
1) add this licence in the official distribution of the ODN 
2) make the possibility to add a new own licence

**Comment by skrchnavy** [comment]
List of licenses is configurable in production.ini file.
How to extend it manually is described in http://docs.ckan.org/en/ckan-2.3/maintaining/configuration.html#licenses-group-url

Currently we use list defined by CKAN (no changes to default is done), so this list is used: http://licenses.opendefinition.org/licenses/groups/ckan.json.
If we want to support another set, updated json file can be installed in next minor release..

**Comment by hanecak** [comment]
We will stay on same level on this as upstream CKAN.

If you need to add or remove some license in your ODN instance, please follow instructions at:

https://utopia.sk/wiki/pages/viewpage.action?pageId=53379826#FrequentlyAskedQuestions%28FAQ%29-HowcanIchangethelistofdatasetlicenses?
