### ISSUE TITLE
CKAN datastore: no view created

### ISSUE THREAD

**Issue by mvi-eea-sk** [OpenDataNode/open-data-node#154]
In 2.3 CKAN, there is no view generated in resource detail when using dpus:
* relationalToCkan
* relationalDiffToCkan

The resource is created correctly and data is inserted too, only the recline view isn't generated automatically and has to be added manually.

TCID: ODN-78, ODN-79

**Comment by mvi-eea-sk** [comment]
submitted the issue here https://github.com/ckan/ckan/issues/2473

and temporary fixes:
https://github.com/OpenDataNode/UVPlugin-relationalToCKAN/commit/2fac1b2dde6764ad3d1516d070ca38def1647077
https://github.com/OpenDataNode/UVPlugin-relationalDiffToCKAN/commit/dce1cbee9ca4673a8641612f00a46324dea58ec3

**Comment by mvi-eea-sk** [comment]
@Jan-Marcek can you please check, if the appropriate version of these DPU's is used in the release?

**Comment by Jan-Marcek** [comment]
@peterklimo dont forget rise versions of https://github.com/OpenDataNode/ODN-UV-Plugins

**Comment by Jan-Marcek** [comment]
@mvi-eea-sk  it is ok
