### ISSUE TITLE
After installation, user Administrator have invalid configuration

### ISSUE THREAD

**Issue by mkl-eea-sk** [OpenDataNode/open-data-node#155]
- Install Open+Data+Node+v1.0.2.
- Open /midpoint
- Users/List
- select Administrator
- select gearbox under the photo-> show empty fields
- set him new password
- save

What you get is error about mandatory fields. So after installation, the ODN is in invalid state - mandatory fields are not pre-filled. So they are not-so-mandatory-fields.
![screenshot - 06192015 - 08 18 45 am](https://cloud.githubusercontent.com/assets/6399320/8248149/d77805ca-165b-11e5-8147-4930bf2bb717.png)

**Comment by skrchnavy** [comment]
Is this valid also for v1.0.3?

**Comment by mkl-eea-sk** [comment]
This issue is present in clean install ODN v1.0.3

**Comment by peterklimo** [comment]
this can be easily fixed for non-default users which are imported during installation procedure, problem with the user 'Administrator' is that it is created by midpoint system before the installation procedure is performed.
fixed for non default administrator (casadmin) by 366cda0
