### ISSUE TITLE
After installation, I do not know how to log in internal catalog

### ISSUE THREAD

**Issue by mkl-eea-sk** [OpenDataNode/open-data-node#156]
In this wiki
https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3
there is a table of default users created after installation (well, since there is different user for each piece of software, is this even 'CAS'-like solution?), but in fields:
ODN/InternalCatalog	see ODN/CAS	see ODN/CAS	CKAN editor	 	 
Unified Views	see ODN/CAS	see ODN/CAS	Administrator, User	
is "see ODN/CAS".
Where exactly can I see the user and password I can use to log into ODN/InternalCatalog and ODN/UnifiedViews?

**Comment by skrchnavy** [comment]
https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3 updated

**Comment by mvi-eea-sk** [comment]
@skrchnavy what exactly should I fix/do here?

**Comment by mkl-eea-sk** [comment]
Just a note "After installing, go and use the components (log in using casadmin)" would be sufficient in install guide.

**Comment by skrchnavy** [comment]
updated
