### ISSUE TITLE
After installation, which user I am recommended to use to log into various components?

### ISSUE THREAD

**Issue by mkl-eea-sk** [OpenDataNode/open-data-node#157]
After clean installing ODN v1.0.3, which user I am recommended by authors, to use for whole ODN installation? 
In midpoint, there is casadmin. From name, it suggests to be used as admin of CAS (is it true that CAS = midpoint in this case?). And there is administrator. But administrator has "Full name 	midPoint Administrator", which suggests to be used as admin of midpoint... well, which user should I use to log into ODN/IC, ODN/UV ?
Moreover, I am unable to log into ODN/IC using "administrator/5ecr3t" (taken from this wiki https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3).
Moreover, I am unable to log into ODN/IC using "casadmin/Passw0rd" (I have clicked on "Reconcile" as the wiki orders me).

When inspecting in midpoint, user administrator does not have organization, nor role set... could this cause problems? User casadmin, however, has these fields filled in...

**Comment by skrchnavy** [comment]
see updated https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3
Was system updated from 1.0.2 or clean install of 1.0.3?

**Comment by mkl-eea-sk** [comment]
Clean install.

**Comment by Jan-Marcek** [comment]
```
 After clean installing ODN v1.0.3, which user I am recommended by authors, to use for whole ODN installation? 
```
casadmin - https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3

```
Moreover, I am unable to log into ODN/IC using "administrator/5ecr3t"
```
No, please use casadmin. 

```
 which user should I use to log into ODN/IC, ODN/UV ?
```

please use casadmin. 


Hint: you can login into midpoint without cas by  administrator 5ecr3 via https://host/midpoint/login from 
 https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3. 
through cas  use casadmin via https://host/midpoint/ . Both method are possible

**Comment by Jan-Marcek** [comment]
The page https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.0.3 was updated. Feel free to open this issue if you have more related questions.
