### ISSUE TITLE
Pipeline scheduled to run after another pipeline is "not planned" in the internal catalogue

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#161]
When you schedule a pipeline to run after another pipeline (e.g., that produces data the pipeline depends on) and then you go to the *"Pipelines"* tab in the internal catalogue for the dataset, you will see *"Next execution: Not planned"*. This is not true. The pipeline is planned to be executed after another designated pipeline is run.

This may be an error of either the internal catalogue that displays incorrect information or the UnifiedViews API that reports the pipeline as not scheduled.

Context: This issue was discovered in ODN 1.0.3 installed from odn-simple Debian package.

**Comment by mvi-eea-sk** [comment]
to @skrchnavy and @OskarStoffan :
When a pipeline is run after another pipeline, master (UV API) automatically returns the next execution time information as null, so CKAN can't display the information it doesn't get.

The question is what should be done? It should:
1. do some estimation on when it will be started - hard to implement, inaccurate
2. give the execution start of the pipe it is started after? If there is bigger chain of pipelines, the first one? - relatively easy to implement (requires changes only in master API)
3. CKAN should display information like: "Next execution: After pipeline with name 'Some pipeline name'" - requires changes in master API, ckan extension and the JSON sent by master API

**Comment by jindrichmynarz** [comment]
I think the option 3 is the best because it describes exactly how the pipeline is scheduled.

**Comment by mvi-eea-sk** [comment]
@skrchnavy i need someone to decide if this this should be fixed and which suggested solution should be implemented

**Comment by tomas-knap** [comment]
Lets go for option 3)

**Comment by mvi-eea-sk** [comment]
@tomas-knap should it write just generalized message: "After other pipeline(s)"
Or should it write the name of ALL pipelines it is planned after?

**Comment by tomas-knap** [comment]
It should write the particular names of the pipelines it runs after

**Comment by mvi-eea-sk** [comment]
added parameter "afterPipelines" in <host>/{pipelineid}/schedules/~all/scheduledexecutions JSON response:
```JSON
[{
  "start":null,
  "schedule":null,
  "afterPipelines":[
    {"1": "pipeline name for pipe with id 1"},
    {"2": "pipeline name for pipe with id 2"}
  ]
}]
```

or there are no "after pipelines"
```JSON
[{
  "start":"2015-10-10T13:40:42.200+0200",
  "schedule":11,
  "afterPipelines": null
}]
```
UV api change: https://github.com/UnifiedViews/Core/commit/b754bbaea460ad0e28af041fed36c04df61ff409

ckanext-ond-pipeline integration: https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/71a10756dab4d5cbaac0da27a744423e8175a3ec

**Comment by mvi-eea-sk** [comment]
merged, ready for testing
