### ISSUE TITLE
Wrong display of logged in user in ODN/IC

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#166]
I make login into midpoint as user oda. I log into IC and UV as this user.
Consequently I logout from IC and UV. In Midpoint everything stayed like logged, page is opened
but when I didnt click here no detection about logged out.
Then I login into IC as user casadmin.
I click into Midpoint. Still logged as Oda. I create under this user new another user.
Result: In Midpoint there is no detection about changed logged user and when I start to click and I already logged into IC, there's no reason for midpoint to think that now is already logged another user.
![image](https://cloud.githubusercontent.com/assets/10993265/8620193/4a8f1206-271e-11e5-9c39-0bda4ed48e2b.png)

**Comment by skrchnavy** [comment]
This is OK related to concept, all applications in ODN (but midpoint) see you as organization. Tere is wrong display of user in CKAN, shall be fixed (ODN theme issue).

**Comment by eea71** [comment]
The problem is not in showing organization. But this fact complicated to explain it preciously. In Midpoint was logged user Oda Braun. In IC and UV user admin admin.

**Comment by skrchnavy** [comment]
@peterklimo cold be more serious problem ten just wrong display.

**Comment by peterklimo** [comment]
concept is that user is using ODN applications on behalf of an organization. but this concept cannot be used in the midpoint, where user is represented by its username, not organization.
it seems that only problem is that username is not displayed in the IC -similar to UV

**Comment by skrchnavy** [comment]
@peterklimo + @mvi-eea-sk to discuss how to improve theme to display user properly.

**Comment by skrchnavy** [comment]
@mvi-eea-sk is this implemented or not?

**Comment by mvi-eea-sk** [comment]
should be in commit https://github.com/OpenDataNode/ckanext-odn-theme/commit/2b5ea4fbafba9b1e0e8533e2deaaa24ea1091cd0
in the "new" theme its this commit https://github.com/OpenDataNode/ckanext-odn-theme/commit/b8e04106f7af345306b32a19315af65d6acae0ad
so yes this should be present in the ODN_v1.2.0 release
