### ISSUE TITLE
sto_81: Export pipeline as zip file

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/open-data-node#173]
[sto_81: Export pipeline as zip file](https://utopia.sk/wiki/x/MoEuAw)

**Comment by skrchnavy** [comment]
@mvi-eea-sk please report status

**Comment by mvi-eea-sk** [comment]
@skrchnavy  In https://github.com/UnifiedViews/Core/commit/cfe02067b9ea9818e5e84159834b8152e2b1c98d is repaired minor bug that caused that:
* version for used DPU templates was not displayed in the export dialog
* version wasn't exported to zip file (used_dpu.xml)

now, should be fully implemented
