### ISSUE TITLE
'Remove' label of the button for disassociating a pipeline 

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#175]
'Remove' label of the button for disassociating a pipeline is confusing. User may be uncertain whether  pressing that button deletes the pipeline. Should be renamed to 'Disassociate'.

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/d75210fd6c3b8b0a5a1c8c0d0e78451b952550b3 in this issue: https://github.com/OpenDataNode/ckanext-odn-pipeline/issues/14

@eea71 if this wasn't included in CKAN on which you tested this issue, please consult @Jan-Marcek
