### ISSUE TITLE
Run Query Error.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#179]
I run in debug mode Test Pipe 4 - creating table data. In debug info was allowed to run sparql query.
![image](https://cloud.githubusercontent.com/assets/10993265/8697200/744ad818-2af3-11e5-8207-55073ed18716.png)

**Comment by eea03** [comment]
Fixed in https://github.com/UnifiedViews/Core/commit/bd7a82c50d1701ccb29e0c7ea66ece199b65f641

**Comment by skrchnavy** [comment]
To check if this is included in release of UnifiedViews Core 2.1.2 or 2.2.0.

**Comment by skrchnavy** [comment]
Included in https://github.com/UnifiedViews/Core/releases/tag/UV_Core_v2.1.2

**Comment by eea71** [comment]
in pre-release 1.1.2 seems is ok!

**Comment by skrchnavy** [comment]
@eea71 to retest in released version
