### ISSUE TITLE
Default set of DPU templates is not complete 

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#180]
There are missing DPUs in the list of default DPU templates after ODN installation.

TC ID: ODN-352

**Comment by peterklimo** [comment]
fixed in the 1.1.1

**Comment by skrchnavy** [comment]
@peterklimo are there all DPU templates from Plugins repository? please chek with @eea03

**Comment by skrchnavy** [comment]
Not properly fixed in 1.1.1, odn-plugins v1.1.2 to be released

**Comment by eea71** [comment]
Checked this:
5 x extractor
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-e-filesFromCKAN-*.jar"
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-e-relationalFromCKAN-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-e-distributionMetadata-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-e-filesDownload-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-e-relationalFromSql-*.jar"



20 x transformer
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-filesFilter-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-filesMerger-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-filesRenamer-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-filesToRdf-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-filterValidXml-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-gunzipper-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-gzipper-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-metadata-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-rdfMerger-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-rdfToFiles-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-rdfValidator-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-relational-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-sparqlConstruct-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-sparqlSelect-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-sparqlUpdate-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-tabular-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-tabularToRelational-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-unzipper-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-xslt-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-t-zipper-*.jar"

10 x loader
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-l-filesToParliament-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-l-filesToVirtuoso-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-l-filesUpload-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-l-rdfToVirtuoso-*.jar"
install_dpu "/usr/share/unifiedviews/dist/plugins/uv-l-relationalToSql-*.jar"
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-l-filesToCkan-*.jar"
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-l-rdfToCkan-*.jar"
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-l-rdfToVirtuosoAndCkan-*.jar"
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-l-relationaldiffToCkan-*.jar"
install_dpu "/usr/share/unifiedviews/dist/odn_plugins/uv-l-relationalToCkan-*.jar"

seems is ok in pre-release 1.1.2

**Comment by skrchnavy** [comment]
@eea71 to retest in released version
