### ISSUE TITLE
Information about resource.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#181]
There is redundancy of displaying data at the resource detail. For example format, created ... is twice. Next thing is case of first letter. Once is UpperCase once is LowerCase. Please do review of this data.
![image](https://cloud.githubusercontent.com/assets/10993265/8716625/59281e10-2b93-11e5-9bc1-723844e2ff25.png)

**Comment by skrchnavy** [comment]
@mvi-eea-sk please check if we are using proper names.

**Comment by mvi-eea-sk** [comment]
@skrchnavy as you can see here: https://github.com/OpenDataNode/odn-ckan/blob/odn/release-v2.3/ckan/templates/package/resource_read.html#L157-L174

Last updated, Created, Format, License are hardcoded and are shown no matter what. And then all parameters are shown even the previously mentioned.

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that:

1. bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older)
2. this behaviour is from upstream (CKAN), so if it is deemed a bug again, we will raise it with upstream

Having said that, whoever is negatively affected by this again in the future, please reopen this.
