### ISSUE TITLE
Localization to Slovak language - corrections.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#182]
There is document for right translation to Slovak language. In this moment there is difference between existing and wished translation.

https://docs.google.com/spreadsheets/d/1XzmBDf0X-lwQ7BcenzYvNembPS3bKLjS-pIfnA3JET8/edit#gid=0

![image](https://cloud.githubusercontent.com/assets/10993265/8743255/7455cc2a-2c6d-11e5-95c2-6dacae9a20e8.png)

**Comment by skrchnavy** [comment]
Translations of CKAN are kept in https://www.transifex.com/projects/p/ckan/
Slovak translation was done in ckan/ckan/#1837.

**Comment by peterklimo** [comment]
user created by default is assigned to organization comsode, which is created by default during installation
