### ISSUE TITLE
User management in UV is enabled.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#183]
In UV is possible to create new user - via Settings(Nastavenia/Sprava pouzivatelov). All user settings has to be done through Midpoint. 
![image](https://cloud.githubusercontent.com/assets/10993265/8746651/d5d85512-2c8b-11e5-8892-6e58138defb3.png)

**Comment by peterklimo** [comment]
fixed in the 2.1.1 release

**Comment by eea71** [comment]
In pre-release 1.1.2 seems is ok!

**Comment by skrchnavy** [comment]
@eea71 to retest in released version
