### ISSUE TITLE
Midpoint - error when resource OpenLDAP is opening 

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#187]
When a user opens resource OpenLdap then an error is shown
![bug](https://cloud.githubusercontent.com/assets/5822680/8821017/a58c9ada-305a-11e5-8556-e9d0bbc2fa54.png)

error:
![bug2](https://cloud.githubusercontent.com/assets/5822680/8821031/c8be4c2e-305a-11e5-8480-ea6ec3fa8fc5.png)

Version: 3.4-odn1.1.0

**Comment by hanecak** [comment]
This is not happening in ODN 1.6.0 (odn-midpoint_1:3.3.1-odn1.6.0). Thus closing.
