### ISSUE TITLE
change of password needs to be easier

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/open-data-node#188]
**When user logs into ODN (private parts: internal catalog, UnifiedViews, midPoint) it is not easy to find where and how to change his password (i.e. I'm talking about user story "I'm logged in and I want to change my password").** Current steps are as follows:

1. log in into http://odn/internalcatalog/
2. click "Tools > User Management
3. click "Users > List users"
4. find "me" and click "me"
5. click "Show empty fields" in menu of one of the gear icons
6. only then I can see and fill in my new passwords into input fields
7. click "Save"

This is quite long process and not easy to find without looking through documentation or asking around.

**Please, implement some easier way.** For example ODN/PublicCatalog (that public one, where SSO is not empoyed) does that in following way:

1. I log in (it is my ODN, so I use 'admin' to get in)
2. I see my dashboard where I can click "Edit settings"
3. there I can change my password

**Comment by hanecak** [comment]
Screenshot for step 3:
![screenshot-1](https://cloud.githubusercontent.com/assets/1419799/8827449/f3cf2e10-308c-11e5-97d1-f14ada25204d.png)

Screenshot for step 4:
![screenshot-2](https://cloud.githubusercontent.com/assets/1419799/8827455/ff0ca014-308c-11e5-805d-298ba8ee90a5.png)


Screenshot for step 5:
![screenshot-3](https://cloud.githubusercontent.com/assets/1419799/8827424/d70a30b8-308c-11e5-8821-c400a76d1540.png)

Screenshot for step 6:
![screenshot-4](https://cloud.githubusercontent.com/assets/1419799/8827436/e6128a38-308c-11e5-8232-9239cd91ed40.png)

**Comment by OskarStoffan** [comment]
If you mean only changing your own password (not changing someone else's password by admin) this can be easily done by clicking your username in the upper right corner and select 'Reset passwords'.

**Comment by hanecak** [comment]
After update of ODN/midPoint (see #253) password change is more intuitive, using Tools > User Management > Credentials screen (see https://utopia.sk/wiki/display/ODN/modify+user's+own+user+profile).

Note: This is duplicate of #193.
