### ISSUE TITLE
Undocumented change of SPARQL endpoint's URL

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#189]
ODN 1.1.0 no longer supports the originally used URL for SPARQL endpoint at <http://localhost:8890/sparql> and replaces it with <https://localhost/sparql> (i.e. specific port is removed and HTTPS is used instead of HTTP). This change can break some existing pipelines that have the SPARQL endpoint's URL in their configuration (e.g., using e-sparqlEndpoint). I failed to find documentation for this change at <https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.1.0>. As it is a potentially breaking change, it should be documented.

**Comment by skrchnavy** [comment]
http://localhost:8890/sparql  shall be supported from internal http requests.
https://localhost/sparql is only redirect to http://localhost:8890/sparql  (see https://github.com/OpenDataNode/odn-box/blob/master/apache/odn-simple-ssl-apache.conf#L188).
So I expect virtuoso is not running.

Anyway you shall not use this internal port when not necessary but to use standard way to access resources.

**Comment by mkl-eea-sk** [comment]
If you need to access triples in internal RDF store, we should consider 
providing e-rdfFromVirtuoso (counterpart of l-rdfToVirtuoso) which may
1. be faster
2. user standard api
3. access virtuoso using localhost loopback interface :1111 instead of 
routing traffic through outside https:// interface
4. be multithreaded

**Comment by jindrichmynarz** [comment]
@skrchnavy: My point was not about Virtuoso not running (it is running), but about an undocumented change that might break some pipelines. Simply put, previously in ODN <http://localhost:8890/sparql> was the only way to access Virtuoso's SPARQL endpoint. Since ODN 1.1.0 this URL is no longer available (connection refused). To be more precise, it is available for localhost requests, but not for public ones. Instead, <http://localhost/sparql> and <https://localhost/sparql> are enabled for accessing the SPARQL endpoint. Therefore, I would expect this change to be at least documented in the ODN 1.1.0 release notes.

**Comment by jindrichmynarz** [comment]
@mkl-eea-sk: I haven't found the e-rdfFromVirtuoso DPU. Where is it? If there's a dedicated DPU for extracting data from Virtuoso, I will use it.

**Comment by mkl-eea-sk** [comment]
But UV / dpu rdfFromSparql can access localhost:8890 am I right?
Of course, you, as external entity browsing ODN cannot access internal port.

**Comment by mkl-eea-sk** [comment]
Some com. noise between us. I meant we should implement e-rdfFromVirtuoso if you need it, not that we have got it (and not told you:)

**Comment by jindrichmynarz** [comment]
You're right. e-sparqlEndpoint can still access <http://localhost:8890/sparql>. Therefore, existing pipelines will not break.

However, since the original SPARQL endpoint's URL is not accessible via browser, which pipeline developers would typically use to access the SPARQL endpoint, then I believe this change should be documented, so that users can be pointed to the new URL.

Regarding the e-rdfFromVirtuoso, I misread your comment. I would only create such DPU if e-sparqlEndpoint proves to be insufficient for some demanding task.

**Comment by skrchnavy** [comment]
@jindrichmynarz there is no change we made in configuration related to [http://localhost:8890/sparql](http://localhost:8890/sparql) This shall be accessible from DPU if UV installed at same server as (as wrote @mkl-eea-sk).
The only change is that Virtuoso listens only on localhost for port 8890, not accessible from external sites.
(https://github.com/OpenDataNode/odn-box/commit/5aa48af214be5f720366eae997f5df9295b1e337#diff-9aaaa16ff5d7475e1608f59a0cd42359R165)

And default url for sparql endpoint stored in CKAN is https://$HOSTNAME/sparql as you can see in https://github.com/OpenDataNode/odn-box/commit/5aa48af214be5f720366eae997f5df9295b1e337#diff-83ecdbd95b178f9c873709daf9c40f47L143

**Comment by jindrichmynarz** [comment]
Sure, as I wrote above, the only change is that Virtuoso listens only to localhost for the port 8890. Still, this was not the case before ODN 1.1.0 and should be documented in release notes. Doing that you may avoid confusing users like me, who got used to <http://localhost:8890/sparql> being publicly accessible.

**Comment by skrchnavy** [comment]
http://localhost:8890/sparql was not publicly accessible, only http://host:8890/sparql and this was error.
solved as a bug in: OpenDataNode/odn-box#21

**Comment by jindrichmynarz** [comment]
If it was a bugfix, then it should be documented as such.

**Comment by skrchnavy** [comment]
https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.1.0 - it defines that this release contains implementation of:
* sto_55: Retrieving public data via SPARQL endpoint
* sto_56: Retrieving data via SPARQL endpoint

I don't know how to report bugfix to featuire that was not supported in previous release.

**Comment by jindrichmynarz** [comment]
To certain extent this feature was supported in the previous release on <http://{hostname}:8890/sparql> (besides the integration via l-rdfToCkan loader). So, from a perspective of a person who used this feature (unknowingly) before it was officially available it is, indeed, an undocumented change. However, you are right that for other users this should be treated as a new feature.

At this point, I don't mind if this change remains undocumented or not. We can close this issue.

**Comment by jindrichmynarz** [comment]
BTW, why is the Virtuoso Conductor (<https://{hostname}/conductor>) made publicly accessible and not only via the localhost interface? If the default Virtuoso credentials (dba/dba) are left unchanged, anyone can log in and change Virtuoso's settings.

**Comment by Jan-Marcek** [comment]
@jindrichmynarz A user is asked to enter Virtuoso credentials during installation.

**Comment by hanecak** [comment]
http://localhost:8890/sparql is undocumented, internal URL for SPARQL endpoint provided by ODN instance and is (still) usable in the pipelines running on that same instance => no need to do anything.

Official SPARQL endpoint accessible via http://hostname/sparql (or for pipelines on that same ODN instance via http://localhost/sparql) is a new feature in ODN 1.1.0 => no need to document a change, as SPARQL endpoint was not officially provided by ODN 1.0.x .

Note: Yes, change occurred, but for undocumented internal feature. Sorry for inconvenience but we hopefully kept it "in family" so no big harm done to wider ODN user community.
