### ISSUE TITLE
ODN CKAN style displays distribution shortcuts in dataset list wrong

### ISSUE THREAD

**Issue by jakubklimek** [OpenDataNode/open-data-node#191]
This is how it looks like:
![image](https://cloud.githubusercontent.com/assets/718827/8929811/736b5672-3528-11e5-8baf-ed84ee1c9f5e.png)
This is how it should look like:
![image](https://cloud.githubusercontent.com/assets/718827/8929831/a167081e-3528-11e5-9f01-836cf84a7be0.png)

**Comment by skrchnavy** [comment]
@rskultety please report status

**Comment by skrchnavy** [comment]
odn theme updated
