### ISSUE TITLE
Forced reload of UnifiedViews when visiting the internal catalogue

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#192]
When I open a pipeline in UnifiedViews in one browser tab and open the internal catalogue (`/internalcatalog`) in another browser tab, then UnifiedViews is forcibly reloaded (the warning *"Communication problem: Take note of any unsaved data, and click here or press ESC to continue"* is shown). If the pipeline has unsaved changes, then these changes are lost.

Frequently, it is useful to have both UnifiedViews and the internal catalogue open, so that a pipeline creator can examine the effect of loaders etc. I would be useful if sessions were handled in a way that enables this.

This issue may be related to UnifiedViews/Core#165.

Context: ODN 1.1.0.

**Comment by jindrichmynarz** [comment]
Note: This also happens when `/sparql` is opened in another browser tab. This might suggest that this is an issue of [OpenDataNode/odn-cas](https://github.com/OpenDataNode/odn-cas).

**Comment by eea71** [comment]
In ODN 1.2.0 I can't simulate this. Seems is ok.
