### ISSUE TITLE
Change 'Reset passwords' to 'Change passwords' in ODN/MidPoint

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#193]
![untitled](https://cloud.githubusercontent.com/assets/8984799/8955701/6d80cfe0-35ef-11e5-93cb-3383e55e98ed.jpg)

**Comment by hanecak** [comment]
After update of ODN/midPoint (see #253) password change is more intuitive, using Tools > User Management > Credentials screen (see https://utopia.sk/wiki/display/ODN/modify+user's+own+user+profile).
