### ISSUE TITLE
Link that redirects back to ODN/InternalCatalog is missing in ODN/UnifiedViews

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#194]
There should be a button in main menu of ODN/UV dedicated to redirect user back to ODN/IC.

**Comment by peterklimo** [comment]
It is possible to set link using following properties
external.menu.link.name = Katal\u00F3g data.gov.sk
external.menu.link.url = http://data.int.edov.globaltel.sk:5000/

**Comment by skrchnavy** [comment]
to include into UV configuration in ODN-BOX.

**Comment by peterklimo** [comment]
see 008f75d
