### ISSUE TITLE
It is not possible to display preview of a resource (CSV and Excel files) for private dataset 

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#197]
For resources containing file dump stored in CKAN's file store, the DataProxy service is not able to preview data contained in the file in case the visibility of a dataset is set to 'Private'.

**Comment by hanecak** [comment]
If not mistaken (issue is too old and details sketchy) this affects "private installations", i.e. those not seen from outside (over Internet). And that seems to be known limitation to CKAN, see http://extensions.ckan.org/extension/datapreview/#problems .

If the problems becomes pressing, we may try to somehow obtain the fix used by data.gov.uk .
