### ISSUE TITLE
It is not possible to remove filter from Data Explorer preview.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#198]
I created pipeline with REST API output. In Data Explorer I see Table with Data. At the top of Data Explorer is possibility to Add Filter, but I cant remove it.
![image](https://cloud.githubusercontent.com/assets/10993265/8983147/10ab6f4e-36c8-11e5-8a6c-79c1887b3fc9.png)

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that:

1. bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older)
2. this behaviour is from upstream (CKAN), so if it is deemed a bug again, we will raise it with upstream

Having said that, whoever is negatively affected by this again in the future, please reopen this.
