### ISSUE TITLE
It is not possible to display preview of a resource (CSV and Excel files) if the size of the file previewed exceeds some (unknown) limit.

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#199]
This is due to response timeout set for this external service (DataProxy). Anyway, CKAN's official documentation clearly states that support for the DataProxy will be dropped on future CKAN releases, so we will need to store these files in CKAN's Data Store in order to make data preview available.

**Comment by skrchnavy** [comment]
It is necessary to discuss how we plan to support preview for csv. There are few options:
* csv stored in data-store
* https://github.com/datagovuk/ckanext-datapreview for preview without external service

**Comment by hanecak** [comment]
That is a limitation in CKAN. Given performance and security constrains of such a limit, its hard to fix. Default limit is 5MB. If big files are used and server has enough memory, limit can be increased by setting bigger value for `ckan.datapreview.limit`.

See http://extensions.ckan.org/extension/datapreview/#limit for more information.
