### ISSUE TITLE
Search is twice in Users menu.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#200]
I clicked at icon comsode (user) and then I clicked at the link Users. It shows next thing.
![image](https://cloud.githubusercontent.com/assets/10993265/8984191/5a950cf2-36d0-11e5-8061-c28431895927.png)

**Comment by mvi-eea-sk** [comment]
fixed: https://github.com/OpenDataNode/odn-ckan/commit/57e4317e2078400a20a3a04cb76eb76dc18a5696

**Comment by eea71** [comment]
in fix 1.1.2 is ok
