### ISSUE TITLE
When creating external catalog for dataset, user has to have at least admin persmissions within organization in order to make the synchronization between ODN/IC and external catalog possible.

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#204]
This is because the verification process of external catalog fails when API key of the user with lower persmissions (editor) is entered, even though editor has enough rights to create or edit datasets. 

ODN-388
ODN-390

**Comment by eea71** [comment]
Tested with this data:
editor:
https://demo.comsode.eu
f6ea6209-9353-40b6-aed5-ab702a277202
org.: comsode

admin
https://demo.comsode.eu
a89bca66-4932-4889-882d-2b7638f1593f

seems in pre-release 1.1.2 is ok

**Comment by eea71** [comment]
admin and also changed to editor

https://demo.comsode.eu
1d2dc250-1c8f-4685-bee4-c2136799fbe9

**Comment by skrchnavy** [comment]
Understood it works so closing
