### ISSUE TITLE
Different result in fulltext seach for public datasets in internal catalogue.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#205]
I simulate situation when all datasets are public. I tried search from 2 different places.
From link Datasets and then from link  Organizations/comsode. Initially I saw all datasets at the screen without search key. Consequently I obtained different results.
![image](https://cloud.githubusercontent.com/assets/10993265/9112060/92d8b36c-3c4c-11e5-88c3-f438401dafa3.png)

ODN - 21

**Comment by peterklimo** [comment]
it seems that there is a bug in ckan. it creates different query requests where is forces solr to use different query analysers and then solr returns different results.

**Comment by peterklimo** [comment]
@mvi-eea.sk please look how the solr queries are constructed in ckan, look for word dismax. do not forget that this problem occurs in both public and internal catalogue

**Comment by peterklimo** [comment]
simple solution how to unify search results in both catalogs is to comment out following code:
https://github.com/OpenDataNode/odn-ckan/blob/odn/release-v2.3/ckan/lib/search/query.py#L347-L355

**Comment by eea71** [comment]
in fix 1.1.2 seems is ok
