### ISSUE TITLE
Problem with importing existing pipeline.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#207]
I exported pipeline and consequently the same I wanted to import. I expected question about overwriting. Result was error.
![image](https://cloud.githubusercontent.com/assets/10993265/9243974/ea16145e-4196-11e5-845f-432ef6cacd15.png)

The next thing is, when I created export I couldn't set the name of file. In such case I would write another name and maybe was not problem with importing. It is up to discussion.

**Comment by eea71** [comment]
Small research. I renamed exported zip. Changed name. Consequently I wanted to import changed file. Error was the same. :-(

**Comment by tomas-knap** [comment]
Already reported as https://github.com/UnifiedViews/Core/issues/474

**Comment by mvi-eea-sk** [comment]
fixed in PR: https://github.com/UnifiedViews/Core/pull/523
