### ISSUE TITLE
sto_82v1: Import pipeline from zip file containing no DPU JARs

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/open-data-node#210]
[sto_82v1: Import pipeline from zip file containing no DPU JARs](https://utopia.sk/wiki/x/BAFwAw)

**Comment by mvi-eea-sk** [comment]
@skrchnavy is milestone correctly set?

**Comment by skrchnavy** [comment]
yes, OpenDataNode v1.2.0
