### ISSUE TITLE
Installation may go wrong with multiple with different FQDNs

### ISSUE THREAD

**Issue by spinque** [OpenDataNode/open-data-node#211]
ODN 1.1.2

The installation takes the output of `hostname -A` as the FQDN to be used as the primary ODN name.

However, `hostname -A` can return more than one FQDN, in which case the concatenation of the two is used (which goes very bad as you can imagine).

In my case, I had two interfaces, one DHCP and one with manual.
Although  `/etc/hostname`, `/etc/hosts` and `/etc/resolv.conf` were setup correctly, the output of `hostname -A` was
```
odn.local odn.spinque.com
```
Starting the ODN installation with this configuration, everything has been configured for host `odn.localodn.spinque.com`.

**On the `.local` domain name**
After quite some effort I found out that that stupid `.local` domain was added by the `avahi` daemon. Once I disabled it, `hostname -A` finally returns only `odn.spinque.com`.
Perhaps it should be advised in the installation instructions to disable `avahi`.

**Comment by hanecak** [comment]
1. We should use only the first FQDN returned by `hostname -A`
2. We should update the installation instructions telling admins to check and make sure that `hostname -A` is returning desired FQDN as first one.
