### ISSUE TITLE
Wrong link at Pipelines tab@internal catalog ?

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#212]
![bug](https://cloud.githubusercontent.com/assets/5822680/9764650/8b930754-5710-11e5-8609-5f7ae4983490.png)

When a user clicks on Running it opens "Scheduler" at UnifiedViews - where the user can find nothing useful because pipeline is running (or is queued ). I think link to its execution makes more sense.

Please, improve this or explain why it is good to see "Scheduler" instead of "Execution"

**Comment by mvi-eea-sk** [comment]
fixed: https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/7e1514cfc54456a427b941e73494cc7155eb7754
* when pipeline runned/queued link is pointing to concrete execution
* otherwise link is pointing to scheduler

**Comment by Jan-Marcek** [comment]
I think Last execution shall point to concrete execution as well.

**Comment by mvi-eea-sk** [comment]
it does ...
you can click on the status, for example the pipeline did run succesfully. The last execution status would be OK and link would be {host}/#!ExecutionList/exec={exex_id}
it should be according user story.

**Comment by Jan-Marcek** [comment]
all right then :)
