### ISSUE TITLE
Intro page in Public catalog contains some strange data.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#220]
![image](https://cloud.githubusercontent.com/assets/10993265/10241267/016a1aac-68e7-11e5-95c0-0260fafb0721.png)

Version is not 1.1 but 1.2, and sample data text Im not sure is ok. Better would be empty place.

**Comment by hanecak** [comment]
IIRC already fixed. We will retest in ODN 1.2.1 .

**Comment by hanecak** [comment]
ODN documentation has been updated regarding how to customize default catalogue home pages, see:

https://utopia.sk/wiki/display/ODN/manage+default+content+of+public+catalog+welcome+screen
