### ISSUE TITLE
Intro page in Internal catalog contains some strange data.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#221]
![image](https://cloud.githubusercontent.com/assets/10993265/10241297/4c42d6a4-68e7-11e5-8437-a68519b9283c.png)
Same as in PC - version and sample data text.

**Comment by hanecak** [comment]
This is intended behaviour for resh installation of ODN - user (ODN owner) is supposed to customize that, for example by:
1. putting some usage instructions into ODN/InternalCatalog (IC)
2. putting some welcome message and link to homepage of his organization into ODN/PublicCatalog (PC)

As this was filled for ODN 1.1, I'm leaving the issue open for now. We will re-test it on ODN 1.2.x plus add information about "steps needed to customize the content" for both IC and PC into User Manual.

**Comment by hanecak** [comment]
ODN documentation has been updated regarding how to customize default catalogue home pages, see:

https://utopia.sk/wiki/display/ODN/manage+default+content+of+public+catalog+welcome+screen
