### ISSUE TITLE
Missing uv-e-rdfFromSPARQL DPU in UV canvas.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#227]
According Test Case ODN-406 DPU Template has to contain  uv-e-rdfFromSPARQL DPU.
This DPU is in 1.2 missing.
![image](https://cloud.githubusercontent.com/assets/10993265/10278497/0aa48db8-6b5e-11e5-88a0-5da365c6c9c4.png)

**Comment by skrchnavy** [comment]
There is DPU e-sparqlEndpoint that shall replace e-rdfFromSparql (see https://github.com/UnifiedViews/Plugins/blob/master/e-sparqlEndpoint/doc/About.md)

**Comment by tomas-knap** [comment]
Yes, this DPU was replaced by e-sparqlEndpoint

**Comment by tomas-knap** [comment]
Please adjust the test case, then it can be closed

**Comment by OskarStoffan** [comment]
Changes made in Test Case ODN-406
