### ISSUE TITLE
Tabular preview at public catalog is not running.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#228]
I created pipeline, associate it with dataset and execute. In IC is this result.
![image](https://cloud.githubusercontent.com/assets/10993265/10303655/81b88cb2-6c15-11e5-8648-e9a5b3b7576f.png)
In PC is next result.
![image](https://cloud.githubusercontent.com/assets/10993265/10303667/957cdbcc-6c15-11e5-9a44-a405164710f1.png)
Note: dataset is public.

**Comment by Jan-Marcek** [comment]
The possible problem could be caused by bug in synchronization - https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync.

**Comment by mvi-eea-sk** [comment]
commit: https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/b1e56efef539e68aed53793a07f1bfad57de494e
