### ISSUE TITLE
Synchronization with public catalog throws errors.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#229]
I made action Synchronize with PC now - Dataset/Manage/Publishing.
![image](https://cloud.githubusercontent.com/assets/10993265/10303770/538cb038-6c16-11e5-9843-b67bea07dc4a.png)

**Comment by mvi-eea-sk** [comment]
fixed: https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/b1e56efef539e68aed53793a07f1bfad57de494e
