### ISSUE TITLE
Missing configuration parameters in backend.properties

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#231]
When a pipeline uses uv-l-rdfToVirtuosoAndCkan, it returns a nullpointerexception error, this is caused by missing configuration parameters in backend.properties

The following properties are missing:

dpu.l-rdfToVirtuoso.username
dpu.l-rdfToVirtuoso.password
dpu.l-rdfToVirtuoso.jdbc.url
dpu.uv-l-rdfToVirtuosoAndCkan.dataset.uri.pattern
dpu.uv-l-rdfToVirtuosoAndCkan.resource.name

Tested on ODN v 1.2.0
TC ID: ODN-68, ODN-70, ODN-72, ODN-74.

**Comment by Jan-Marcek** [comment]
I have just tasted with the parameters in backend.properties and it has worked.
```
dpu.l-rdfToVirtuoso.username = dba
dpu.l-rdfToVirtuoso.password = dba
dpu.l-rdfToVirtuoso.jdbc.url = jdbc:virtuoso://localhost:1111/charset=UTF-8/
dpu.uv-l-rdfToVirtuosoAndCkan.dataset.uri.pattern = https://host/internalcatalog/dataset/${id}
```

**Comment by OskarStoffan** [comment]
Yes, it works when the parameters are set in /etc/unifiedviews/backend-config.properties, tested on ODN v 1.2.0

**Comment by Jan-Marcek** [comment]
fixed. please,  look on the https://github.com/OpenDataNode/odn-box/issues/42 for more information
