### ISSUE TITLE
No tabular preview is available in IC (using uv-l-relationalToCkan)

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#235]
The resource is created correctly in CKAN's datastore - both REST API and CSV file dump are OK (tabular preview is missing only).  
![2](https://cloud.githubusercontent.com/assets/8984799/10709878/9733983e-7a3e-11e5-9cd1-972605cedf02.png)

**Comment by hanecak** [comment]
Looks like clone of #119 which is closed (see https://github.com/OpenDataNode/open-data-node/issues/119#issuecomment-170850197) thus closing also this.
