### ISSUE TITLE
Problem file upload on IC from UV

### ISSUE THREAD

**Issue by cremarco** [OpenDataNode/open-data-node#236]
I have to upload a file in the internal catalog but UV returns this error.
Response:{"help": "../internalcatalog/api/3/action/help_show?name=internal_api", "success": false, "error": {"__type": "Validation Error", "upload": ["File upload too large"]}}

It is a N3 file (about 200MB).
Some indication on how to solve this problem?

**Comment by hanecak** [comment]
You need to raise the limit on file size (which is by default 10MB). Please follow instructions in FAQ: "*How can I load files bigger than 10 MB (CKAN default)?*"

https://utopia.sk/wiki/pages/viewpage.action?pageId=53379826#FrequentlyAskedQuestions%28FAQ%29-HowcanIloadfilesbiggerthan10MB%28CKANdefault%29?
