### ISSUE TITLE
"Sample data" at the ODN screen.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#240]
I login to ODN, then I click to ODN icon at the top. I obtained this screen.
![image](https://cloud.githubusercontent.com/assets/10993265/12229706/94f0096e-b84a-11e5-8737-0fa4cf6dac39.png)

**Comment by Jan-Marcek** [comment]
odn-simple: 1.2.3

**Comment by Jan-Marcek** [comment]
duplicated:  https://github.com/OpenDataNode/open-data-node/issues/221

**Comment by hanecak** [comment]
ODN documentation has been updated regarding how to customize default catalogue home pages, see:

https://utopia.sk/wiki/display/ODN/manage+default+content+of+public+catalog+welcome+screen
