### ISSUE TITLE
record count in IC and PC is different

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/open-data-node#242]
OpenData.sk is running ODN at http://odn.opendata.sk/ to collect some datasets from others.

One of mirrored datasets is "Vestník verejného obstrávania od roku 2006" published by Aliancia Fair-
Play.

Original `procurements.csv` has (as of 11.1.2016) 75273 records.

Pipeline (https://opendata.in.eea.sk/unifiedviews/#!PipelineEdit/2) is pushing contents of that file also to DataStrore using `uv-l-relationaldiffToCkan`.

**And now the problem:**
- internal catalog (IC) is reporting 75273 records, which is correct (see https://odn.opendata.sk/internalcatalog/dataset/datanest-2-mirror/resource/e401aac7-500f-4990-8274-a2d57fabdb9c)
- **public catalog (PC) is reporting 50000 records, which is incorrect** (see http://odn.opendata.sk/dataset/datanest-2-mirror/resource/ea9b28eb-da22-4594-9fb7-4609e8507982)

Given the "nice and round" 50000 number I guess this might be some limitation in IC->PC sync or PC configuration.

And 50000 records seems to be actual content of the resource in PC, see results of "count" API call:
- http://opendata.in.eea.sk/api/action/datastore_search_sql?sql=SELECT%20count%281%29%20from%20%22ea9b28eb-da22-4594-9fb7-4609e8507982%22

Can you please check?

(note: I'll provide access credentials for ODN.opendata.sk via other means as those are private)

**Comment by mvi-eea-sk** [comment]
This is more of a performance issue than a bug.
The datastore synchronization is done in chunks of size 50000 rows per request.
Issues found:
* the chunk is just too big and can in some situation cause out of memory issue
* apache: the number of server processes started and allowed to start can reduce the memory available
* nginx: (parameter: keepalive_timeout 65;) the default request timeout is 65 sec, so if the synchronization request last too long, the whole synchronization interrupted

The good news the solution is simple, just make the the chunk smaller. This will cause more request will be sent, but that shouldn't be problem.

Again i filled wrong issue number in the commit, causing it not to be linked here properly. Fix link is here: https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/38b8b7aac3c315e9a91c780c4e3034540b2b0c45
