### ISSUE TITLE
minor packaging clean-up

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/open-data-node#249]
Package description and other stuff was updated to match pattern in other ODN packages:

- odn-box: see https://github.com/OpenDataNode/odn-box/pull/45
- odn-cas: see https://github.com/OpenDataNode/odn-cas/pull/6
- odn-ckan: see https://github.com/OpenDataNode/odn-ckan/commit/d8dd4145cfcf9504c240efeb4ead21cd7d18c735 (*)
- odn-midpoint: see https://github.com/OpenDataNode/odn-midpoint/commit/2525b8ebe2830b5c579e855d03d6483a0084e5cc (*)
- odn-solr: see https://github.com/OpenDataNode/odn-solr/commit/d9690e47c6e1e430928bdca0a4cdf54314ce5dfd (*)
- ODN-UV-Plugins: see https://github.com/OpenDataNode/ODN-UV-Plugins/pull/4

Note to @Jan-Marcek : Given pending updates regarding Debian 8 packaging, merge at your own leisure.

(*) Sorry, I've messed up here by committing into wrong branch thus no pull requests.

**Comment by Jan-Marcek** [comment]
merged

**Comment by hanecak** [comment]
odn-box, odn-cs and odn-ckan seem OK.

odn-midpoint needs a release (ODN_v1.2.1 if I'm not mistaken), odn-solr too (as ODN_v1.1.3)(*) and also ODN-UV-Plugins (ODN_v1.2.3).

Please do those also and then close this issue. Thank you in advance.

(*) As written before, I guess I've commited to wrong branch. Please advice if I need to commit that change somewhere else.

**Comment by Jan-Marcek** [comment]
done. odn-midpoint, odn-solr ,  ODN-UV-Plugins are published
