### ISSUE TITLE
replicate logrotate stuff from Tomcat7 in odn-cas, odn-midpoint, odn-solr, unifiedviews-backend and unifiedviews-frontend

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/open-data-node#257]
In ODN, we have odn-cas, odn-midpoint, odn-solr, unifiedviews-backend and unifiedviews-frontend deployed in their own Tomcat instances. Those are logging to catalina.out, each to their own. But unlike Tomat7, those ODN modules do not ship logrotate settings so the logs is not rotated and grows "forever".

So, please, replicate Tomat7 logrotate stuff in mentioned ODN modules.

More info based on contents of http://anonscm.debian.org/cgit/pkg-java/tomcat7.git/tree/debian :
1. The key file is /etc/logrotate.d/tomcat7 . We need also /etc/logrotate.d/odn-cas, etc. with similar content.
2. Debian's implementation for Tomcat7 is sort of complicated (see `grep -r logrotate .`), but the benefit is that logrotatefile contains actual user and group matching real user and group under which the Tomcat is running, to ensure smooth operation even if sysadmin tweaks those values. It might be an overkill for us, but we should do it same way so as to not confuse sysadmin by doing it differently in our tomcat instances.

This will help us fix https://github.com/OpenDataNode/open-data-node/issues/256 .

**Comment by Jan-Marcek** [comment]
unifiedviews - https://github.com/UnifiedViews/Core/issues/582
