### ISSUE TITLE
Synchronization problem between ic and pc

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#261]
error message:  ```initializer for ctype 'int(*)(int, X509_STORE_CTX *)' must be a pointer to same type, not cdata 'int(*)(int, X509_STORE
_CTX *)'```

![image](https://cloud.githubusercontent.com/assets/5822680/15425744/b8a07e6a-1e8a-11e6-8eaa-1128f38aa031.png)

**Comment by Jan-Marcek** [comment]
relates https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/issues/15

**Comment by Jan-Marcek** [comment]
is fixed by https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/issues/15

**Comment by hanecak** [comment]
Fix included in ODN 1.5.0 .
