### ISSUE TITLE
sto_26: Comments for dataset

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/open-data-node#40]
[sto_26: Comments for dataset](https://utopia.sk/wiki/display/ODN/sto_26%3A+Comments+for+dataset)

**Comment by hanecak** [comment]
IIRC comments should be there but disabled by default, so:
1. verify, whether I do remember correctly
2. update user documentation (and user story) to make clear what the current status is

**Comment by hanecak** [comment]
After digging up in archives, this was descoped from ODN on Oct 5th 2015 => wont fix.

If such functionality is desired, some of the following extensions may be installed in ODN/*Catalog:

- https://github.com/yhteentoimivuuspalvelut/ckanext-ytp-comments
- https://github.com/ckan/ckanext-disqus/
