### ISSUE TITLE
sto_68: Pipeline for publishing tabular data from file as RDF graph accessible via SPARQL queries (wizard)

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/open-data-node#47]
[sto_68: Pipeline for publishing tabular data from file as RDF graph accessible via SPARQL queries (wizard)](https://utopia.sk/wiki/pages/viewpage.action?pageId=50660223)

**Comment by hanecak** [comment]
"Long timer ago" we've decided that we will not implement Wizards, yet.

This decision still holds, so I'm closing this.
