### ISSUE TITLE
Invalid error message if Title missing.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#61]
Add Dataset -> Dont fill nothing - > Err msg = 

The form contains invalid entries:
Name: Missing value

I cant find Name at the Form. Right msg = Missing Title, or missing URL.
The same for err msg:

The form contains invalid entries:
Name: Name must be at least 2 characters long

**Comment by mvi-eea-sk** [comment]
related to #62
title is no required
name is...
name is filled in the URL fill-able box

**Comment by eea71** [comment]
Only please! Correct err msg, because is not OK!

No!
Name missing value! 

BUT
URL missing value!

Name is not present at the form.

**Comment by skrchnavy** [comment]
@eea71 where can I find this behaviour? (some steps to reproduce would be nice)

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older).
