### ISSUE TITLE
dmeo

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#62]
Add Dataset  -> fill Title with something. Save
Add Dataset -> fill Title with the same. Err msg is rised.
Add Dataset -> fill Title with something another. Err msg is rised again.

Strange behaviour. Inspite of fact, that probably Title is UNIQUE I saved twice the same title. ;-)
URL when I retype Title is not changed automatically. Also when I change Title - URL (I dont know why) containst only 1 letter and rised err msg 

The form contains invalid entries:
Name: Name must be at least 2 characters long

**Comment by mvi-eea-sk** [comment]
related to #64
The name of the dataset is automatically created from title
Example:

When creating dataset:
1. you type title: My new dataset
2. corresponding name is created automaticaly (in the URL parameter): my-new-dataset

3. Add another dataset with the same name
4. type the same title => the same name is produced
5. save => error
6. you change the title, but the name stays the same
7. save => error

Btw when you try to save with the same name it says you are trying name (NOT title!) already in use and highlights the field that needs to be changed ...

**Comment by skrchnavy** [comment]
@mvi-eea-sk / @eea71 - is this bug or feature? (I expect this is vanilla CKAN implementation reused in ODN/IC)

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that:

1. bug is truly old (we're actually not supporting anything before actual minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older)
2. this behaviour is from upstream, so if it is deemed a bug again, we will raise it with upstream

Having said that, whoever is negatively affected by this again in the future, please reopen this.
