### ISSUE TITLE
Bad return place after deleting dataset.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#63]
In your Organization  execute action Add Dataset -> Create any dataset with Title only, private and Save it. 
You will see all your datasets for you organization, and also your new dataset.
Click at it and Manage. At the detail click Delete button and confirm.
The right behaviour - > I will be at the list of Organization Datasets, where I was before Detete acion.
Real behaviour = I am at the Datasets tab generally.

**Comment by skrchnavy** [comment]
@mvi-eea-sk Is this feature of vanilla CKAN? Or bug there or bug in ODN-CKAN?

**Comment by mvi-eea-sk** [comment]
I would say its feature.
CKAN doesn't remember you page view history, so it can't know where to redirect to. It's set to redirect to Datasets tab regardless if you came from that tab or Organization datasets tab. Generally dataset doesn't have to belong to organization.

**Comment by skrchnavy** [comment]
@eea71 / @OskarStoffan : is this acceptable behaviour? Is delete dataset expected feature?

**Comment by OskarStoffan** [comment]
According to COMSODE methodology, deletion of a dataset is not an expected feature.

**Comment by skrchnavy** [comment]
There are defined stories #137 and #138 for termination of dataset. So delete button is for now not properly handled based on the stories (not implemented yet).
This issue is closed as wan't fix
