### ISSUE TITLE
Longer Organization and Dataset Name overlaps other text in form.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#65]
I created Dataset with name more than 45 characters (the same for Organization) and this name when I work with this item overlap frame and rewriting another areas. This status is visible in internal catalog, public catalon and ckan demo too.
The same problem is visible when I click at the Organizations button at the top of View. Name overlaps panel for organization.

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/ckanext-odn-theme/issues/3
