### ISSUE TITLE
Insufficient user rights for /var/www/dump for L-FilesToLocalFS

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#66]
I want to publish a file dump for a dataset. When a pipeline containing L-FilesToLocalFS DPU is executed, with 'Destination directory absolute path' set to '/var/www/dump' it fails due to insufficient rights.

**Comment by skrchnavy** [comment]
Depends on https://github.com/OpenDataNode/odn-box#17

**Comment by OskarStoffan** [comment]
DPU was deprecated in 1.0.0 and replaced by uv-l-filesUpload
