### ISSUE TITLE
Invalid URL for created resource

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#67]
I created pipeline with resource on http url. After running pipeline, zip file as resource was saved at the location with invalid url.

data.zip
URL: http://ada/dump/data.zip

instead of 
data.zip
URL: 192.168.128.28/dump/data.zip

TCID: ODN-113, ODM-112, ODN-36, ODN-106, ODN-105, ODN-24

**Comment by skrchnavy** [comment]
@eea71 is this also present in v1.0.2 or is it already fixed?

**Comment by mvi-eea-sk** [comment]
duplicate of #79 which is already closed and fixed
