### ISSUE TITLE
Word "text" still displayed during pipeline creation.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#68]
+ Add pipeline - > at the left frame below ADVICE is still displayed word "text".
![image](https://cloud.githubusercontent.com/assets/10993265/6896039/2a897744-d6e7-11e4-91c3-011d31aa6795.png)

**Comment by mvi-eea-sk** [comment]
fixed in https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/23c1418685465efd52c3ae180bae0b91b89b3d80
will be in 1.0.0 release
