### ISSUE TITLE
LOGOUT button is not properly visible in ODN/UV.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#70]
In mozilla firefox I see something unclear. It is very heavy to read it.
![image](https://cloud.githubusercontent.com/assets/10993265/6895964/494bdccc-d6e6-11e4-8236-65087770a5a9.png)

**Comment by skrchnavy** [comment]
@eea71 - is this also valid for the version 1.0.2?

**Comment by peterklimo** [comment]
word Logout written in white font color, readability improved

**Comment by skrchnavy** [comment]
@peterklimo any reference to commit number or issue in proper repository?

**Comment by peterklimo** [comment]
no this was fixed with new thema, i do not know the exact commit ID, sorry

**Comment by skrchnavy** [comment]
@eea71 to retest
