### ISSUE TITLE
Disassociated pipeline continues to execute according to schedule set previously (scheduling rule is not disabled)  

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#71]
I created pipeline and I associated it with datased. I schedule it every 3 minutes. Then I disassociated pipeline. In scheduler is pipeline still in list. After 4 minutes I saw pipeline was running.

You can see at 192.168.128.28 this:
1) NonAssociated1 pipeline you can see at the list of pipelines you can choose to associate.
2) In scheduler this pipeline is still in list for schedulling.

TCID: ODN-323

**Comment by mvi-eea-sk** [comment]
related to https://github.com/OpenDataNode/ckanext-odn-pipeline/issues/7
fixed in: https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/a2163d5930b8ff22a36a7d102b9f023583f767fe
by disabling schedules when association is removed

**Comment by skrchnavy** [comment]
@mvi-eea-sk  please check what component shall be fixed.

**Comment by mvi-eea-sk** [comment]
fixed: https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/deb126feb1315de23796fb9c7119d7bb3f803e85
