### ISSUE TITLE
UV E-HttpDownload component is more than one.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#72]
I created DPU template from zip file. I created and run many pipelines. Some of them was created manually, the rest as modified copies.Running was also automated and manual too.
After these acions (exactly I dont know which one was critical for it) there is multiplication of UV components. See picture...
![image](https://cloud.githubusercontent.com/assets/10993265/6915305/3b4d4522-d793-11e4-8727-21cf79add1cc.png)

**Comment by skrchnavy** [comment]
looks as reported in UV/Core
* UnifiedViews/Core#487
* UnifiedViews/Core#459
* UnifiedViews/Core#453

Shall be fixed in ODN 1.1.1, @eea71 to retest
