### ISSUE TITLE
Missing POPULARITY item in combo box Order by (internal catalog)

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#74]
In interanl catalog.
Click to Organization. Below the search box is combo box Order by: Item POPULARITY is missing.
![image](https://cloud.githubusercontent.com/assets/10993265/6917266/56a7afaa-d7a3-11e4-8035-3e17dfc2d80e.png)

TCID: ODN-20, ODN-21

**Comment by mvi-eea-sk** [comment]
configuration issue, fixed in https://github.com/OpenDataNode/odn-box/commit/6d47a4c5d1ddc7d34138200d99206cbb92f7e0d6 (release 1.0.0)
it's for both public and internal

**Comment by skrchnavy** [comment]
related also to #77
