### ISSUE TITLE
 Missing CREATOR field at the list of datasets (internal catalog)

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#75]
Click at the organization. Data about datasets are displayed (unorganized). Field creator (inspite of fact was entered) is not displayed.
![image](https://cloud.githubusercontent.com/assets/10993265/6917472/268b7dfe-d7a5-11e4-9416-ba32ade707dd.png)

TCID: ODN-20

**Comment by skrchnavy** [comment]
@mvi-eea-sk is this issue in vanilla CKAN? Or a theming issue?
