### ISSUE TITLE
Incorrect alphabetical sorting of Dataset Names (internal catalog)

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#76]
Internal catalog.
Click Organization and you obtain list of Datasets. You can sort it using combo box Order By:
Alphabetical order of Dataset Name is not ok according me.
Case of letter is not in common life reason to sort the way it is done. 
For example If I have 2 datasets 1. Advent and 2. advent2 these two datasets have to be sorted as letter A. And it is not ok, if I firstly saw all datasets with UpperCase letters and then after "Z" I see "advent2" dataset.

TCID: 
ODN-21
ODN-20:Catalog records browser

**Comment by mvi-eea-sk** [comment]
its one of the "naming" issues
it's sorted by name, not title
name can have only lowercase, _ and - characters
lets say we have datasets with title:
* 'Advent' and name 'advent'
* advent2 and the same name 'advent2'
* 'Advent 3' and name 'advent-3'
* 'Baby' and name 'advent-1'
* no title and name 'advent-0'

will be ordered (by Name Ascending) and displayed:
Advent
advent-0
Baby
Advent 3
advent2

**Comment by eea71** [comment]
Sorry, your example is completely bad sorted. B has to be at the end of list. ;-)

**Comment by skrchnavy** [comment]
@mvi-eea-sk is this default behaviour of vanilla CKAN? Is there a feature for it available that such sorting is expected?

**Comment by mvi-eea-sk** [comment]
@skrchnavy 
yes this is default behaviour

**Comment by skrchnavy** [comment]
could be related to ckan/ckan#912 where also display was incorrect. so probably sorting is wrong.

**Comment by skrchnavy** [comment]
isn't this a fix? ckan/ckan#2086

**Comment by mvi-eea-sk** [comment]
We are talking about dataset sorting not oraganization sorting.

**Comment by skrchnavy** [comment]
Dataset ordering was fixed here: ckan/ckan#1368 (ckan/ckan@3a00b572e795e03b915f6250dfed8b83aad768f7), it was unified to match with the main search (based on the comment in commit).
Please check if it is OK or if we shall report bug against CKAN.

**Comment by mvi-eea-sk** [comment]
problem is that the search is case sensitive @peterklimo is editing solr schema

**Comment by peterklimo** [comment]
solr schema fixed in the odn-simple as well as edem-pa

**Comment by skrchnavy** [comment]
@peterklimo to provide info where it is fixed (commit number or issue in particular repo)

**Comment by eea71** [comment]
Without change.

**Comment by eea71** [comment]
In this moment I see only problems with same titles of Datasets with different case of characters and inserted spaces.

**Comment by skrchnavy** [comment]
@eea71 please report it as low priority bug, this ordering is for now acceptable, probability of using same name of dataset that differs in upper/lower case is very low. Then we can close this issue as solved
