### ISSUE TITLE
Incorrect alphabetical sorting of Dataset Names (public catalog)

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#78]
Click Organization and you obtain list of Datasets. You can sort it using combo box Order By:
Alphabetical order of Dataset Name is not ok according me.
Case of letter is not in common life reason to sort the way it is done. 
For example If I have 2 datasets 1. Advent and 2. advent2 these two datasets have to be sorted as letter A. And it is not ok, if I firstly saw all datasets with UpperCase letters and then after "Z" I see "advent2" dataset.

TCID: ODN-26, ODN-27

**Comment by mvi-eea-sk** [comment]
related to #76

**Comment by peterklimo** [comment]
solr schema fixed in the odn-simple as well as edem-pa

**Comment by eea71** [comment]
Without change.

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/odn-box/commit/a19d85585495f75edeaf16c295ac3daa3d34aaf8
