### ISSUE TITLE
No URL validation for added or modified external catalog

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#80]
There is no validation of URL for added external catalog.
https://utopia.sk/wiki/display/ODN/sto_43%3A+Add+external+catalog+for+update
![url](https://cloud.githubusercontent.com/assets/10993265/6942713/a89ad490-d889-11e4-9ae4-eb20134ccc29.jpg)

TCID: ODN-125, ODN-166

**Comment by skrchnavy** [comment]
@OskarStoffan / @eea71 isn't this related to #50 and #51 (also to user story #135) ?

**Comment by mvi-eea-sk** [comment]
fixedin https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/833e75aaa0d7a09624f03d840b6e31bcbe3f677b
Note: this fix is not catalog verification, only url validation

**Comment by eea71** [comment]
Without change...

**Comment by mvi-eea-sk** [comment]
that fix isn't included in 1.0.3 release and i didn't deploy it to test (ast) server, should i deploy it?
