### ISSUE TITLE
GUI modification for err msg window.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#81]
I created 3 ext. catalogs for publishing tab. 1 and 3 are ok, 2. is bad url. After pushing action synchronize with all ext. catalog now I obtained this screen.
Pls. see x icon for closing red err msg window.
![image](https://cloud.githubusercontent.com/assets/10993265/6943207/be1f758e-d88c-11e4-9d8b-985b6ee15d6a.png)

**Comment by hanecak** [comment]
In an attempt to clean-up our backlog, I'm closing this as "wont fix" given that bug is truly old (we're supporting only most recent minor release, i.e. as of ODN 1.2.5, we're supporting 1.2.x, not older).
