### ISSUE TITLE
Internal catalog: improve the placeholder for dataset URL

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#85]
When using OpenDataNode (version 0.11.0, installed from Debian package), if you want to add a new dataset, then in the step of adding data the input form uses `http://example.com/my-image.jpg` as the placeholder of the URL field. Since JPG image isn't the best example of _data_, this placeholder could be improved; e.g., `http://example.com/my-dataset.csv`.

**Comment by skrchnavy** [comment]
@jindrichmynarz in CKAN 2,3 (used in latest ODN), there is `http://example.com/dataset.json'  (see http://demo.ckan.org/dataset/new u:test p:test).
Is this OK?

**Comment by jindrichmynarz** [comment]
That's certainly better than JPEG.

**Comment by skrchnavy** [comment]
In Add data part is `http://example.com/my-image.jpg`

**Comment by hanecak** [comment]
Still valid for ODN 1.6.2 .

But we would like to avoid having "different CKAN" in ODN. So, please try opening the issue upstream.
