### ISSUE TITLE
Name of ODN instance is not configurable(catalog)

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#86]
Using OpenDataNode (version 0.11.0, installed from Debian package), when you change the configuration of either internal or public catalog at `/internalcatalog/ckan-admin/config` or `/ckan-admin/config` respectively, the changes don't seem to have any impact. For example, changing the "Site Title" or "Style" doesn't result in any noticeable effect.

If this configuration is overridden by ODN configuration, then they would be better disabled in the CKAN configuration. Otherwise, configuration via CKAN administration should be fixed, so that it works.

**Comment by skrchnavy** [comment]
@jindrichmynarz is this relevant also for odn 1.0.X (1.0.2) ?

**Comment by jindrichmynarz** [comment]
In ODN 1.0.2 as casadmin I'm not authorized to access `/internalcatalog/ckan-admin/config`, because we lack CKAN admin user (#151). `/ckan-config/config` in the public catalogue can be access by admin/admin, but it still seems to have no effect. For example, I changed the site's title and observed no change.

**Comment by Jan-Marcek** [comment]
One day I have observed...

It could be caused by the fact that the site title is configured in https://github.com/OpenDataNode/odn-box/blob/master/ckan-pc/production.ini#L104

Probably production.ini could have higher priority than gui

**Comment by skrchnavy** [comment]
I think it works correctly in configuration point of view (title set in DB has higher priority then the value in ini file).
Unfortunately, Site Title (ckan.site_title) is displayed in browser tab / window name) not in the part next to logo.

**Comment by skrchnavy** [comment]
Error Issue title changed to reflect expectation

**Comment by skrchnavy** [comment]
solved using new odn-theme
