### ISSUE TITLE
UV behaves differently in Google Chrome and Mozilla Firefox

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/open-data-node#92]
When accessing a pipeline, the URL displayed contains parameters in Firefox. In Chrome it does not. The behavior is correct only when the parameter is not contained in the URL. (both screenshots were created in Chrome, the second one with the URL copied out from Firefox). 

![1_uv](https://cloud.githubusercontent.com/assets/8984799/7413016/67f73390-ef48-11e4-92f9-eb223bcb39f7.png)
![2_uv](https://cloud.githubusercontent.com/assets/8984799/7413015/67f60f74-ef48-11e4-84a4-9b40a99d632e.png)

**Comment by skrchnavy** [comment]
@OskarStoffan this is https://github.com/UnifiedViews/Core/issues issue, please report problem there.

**Comment by skrchnavy** [comment]
depends on UnifiedViews/Core#379

**Comment by skrchnavy** [comment]
@OskarStoffan are you able to reproduce it with 2.0.2 release?
