### ISSUE TITLE
Midpoint Assignments error.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#93]
Login into midpoint as casadmin. Create new user. Save. Clik check box next to Assignments - ODN and End User. And then next to settings wheel select for example Assign Account or Assign Role. 
![image](https://cloud.githubusercontent.com/assets/10993265/7413954/df04c95a-ef4f-11e4-9ad3-c05b05f40821.png)

**Comment by peterklimo** [comment]
fixed in the new release of midpoint, not reproducable on develop version
