### ISSUE TITLE
Midpoint create user problem.

### ISSUE THREAD

**Issue by eea71** [OpenDataNode/open-data-node#97]
I tried to create new user in midpoint. I filled Name, Given Name and FullName, password at bottom.
![image](https://cloud.githubusercontent.com/assets/10993265/7490104/c248246e-f3dd-11e4-860d-5a5b5c4a486f.png)

TCID: ODN-40

**Comment by katkav** [comment]
You have to fill the family name - it is required by LDAP. For correct user creation it is also required to set the role for the user (you can choose in extension/role - administrator or user).

**Comment by skrchnavy** [comment]
From the gui it is not clear what are mandatory parameters, @katkav is there a way to configure midpoint to change GUI to prevent such issue?

**Comment by katkav** [comment]
Yes, it is possible and actually it was already configured, but this configuration was probably not added to the current release..

**Comment by skrchnavy** [comment]
bug related to #26 (sto_31: New user and it's role)

**Comment by skrchnavy** [comment]
@peterklimo what is status?

**Comment by peterklimo** [comment]
fixed and tested in 1.0.2
